"""first

Revision ID: 01049b1ffd1e
Revises: 070f19bf05e1
Create Date: 2021-08-06 11:08:52.753642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01049b1ffd1e'
down_revision = '070f19bf05e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('last__name', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'user', ['first_name'])
    op.create_unique_constraint(None, 'user', ['last__name'])
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=50), nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'last__name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
